name: AI Agents Automation

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:

jobs:
  marketing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r ai-agents/requirements.txt
      - name: Run Marketing Agent
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          FACEBOOK_TOKEN: ${{ secrets.FACEBOOK_TOKEN }}
          INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
          TIKTOK_TOKEN: ${{ secrets.TIKTOK_TOKEN }}
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
        run: python ai-agents/marketing_agent.py

  content:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.schedule == '0 0 * * 0'  # Every Sunday
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r ai-agents/requirements.txt
      - name: Generate New Course
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
        run: python ai-agents/content_agent.py
      - name: Commit Changes
        run: |
          git config --global user.email "ai-agent@empoweringmoms.com"
          git config --global user.name "AI Content Agent"
          git add config.json
          git commit -m "AI: Generated new course content"
          git push
