name: Social Media Marketing

on:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 9am
  workflow_dispatch:

jobs:
  marketing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r scripts/requirements.txt
      
    - name: Run marketing agent
      env:
        FACEBOOK_TOKEN: ${{ secrets.FACEBOOK_TOKEN }}
        INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
        TIKTOK_TOKEN: ${{ secrets.TIKTOK_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python scripts/ai_agents/marketing.py
