name: Payment Processing

on:
  repository_dispatch:
    types: [payment_received]

jobs:
  process-payment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Process payment
      env:
        PAYFAST_MERCHANT_ID: ${{ secrets.PAYFAST_MERCHANT_ID }}
        PAYFAST_MERCHANT_KEY: ${{ secrets.PAYFAST_MERCHANT_KEY }}
      run: |
        pip install requests
        python payment-processor.py "${{ github.event.client_payload.transaction_id }}" \
          "${{ github.event.client_payload.amount }}" \
          "${{ github.event.client_payload.course_id }}" \
          "${{ github.event.client_payload.user_data }}"
          
    - name: Send course access
      run: |
        python -c "from utils import send_email; send_email('${{ github.event.client_payload.user_data.email }}', 'Course Access', 'Download link: https://yourdomain.com/download/${{ github.event.client_payload.transaction_id }}')"
