name: Security Audit

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3am SAST
  push:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Run security scan
      uses: owasp/zap-full-scan@v0.7.0
      with:
        target: 'https://yourdomain.com'
        rules: 'rules/security-rules.yml'
        
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: zap-report.html
